name: DB Migration

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Run D1 database migration via Wrangler
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: wrangler d1 execute DB --remote --file=./migrations/d1_schema.sql
